apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs-server
spec:
  type: NodePort
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 9072
      nodePort: 30007  
  selector:
    app: nodejs-server
